version: '2.1'

services:
  nette-palette:
    container_name: nette-palette
    image: sidewave/php:7.1-apache
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/demo/www
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./../:/var/www/html